Repository SUSUSSG/PenGreenLiveFrontEnd, pull requests merged in 2024-05, with the labels that each got.

#33 [FEAT] 리뷰 통계 페이지 추가
  src/components/Card/product-historyCard.vue
  src/components/Card/review-statistics-card.vue
  src/components/reivew/reviewchart.vue
  src/constant/appex-chart.js
  src/views/dashboard/review-statistics.vue
  src/views/mypage/order-list.vue
Labels: 버그 수정, 기능추가, CSS, 스타일

#32 [FEAT] 판매자 라이브 일정 화면 추가, 방송 등록 페이지 디자인 변경
  src/components/Card/seller-broadcast-schedule.vue
  src/components/Sidebar/index.vue
  src/router/route.js
  src/views/broadcast/live-register.vue
  src/views/dashboard/live-prepare.vue
Labels: 기능추가, CSS, 리팩토링

#35 [FEAT] 채널 구독 추가
  src/components/Card/schedule-card.vue
  src/components/Header/index.vue
Labels: 기능추가, CSS

#34 [FEAT] 방송 통계 페이지 구현
  src/views/dashboard/broadcast-statistics.vue
Labels: 기능추가, CSS, 스타일

#37 [FEAT] 헤더 디자인 및 환경이야기 추가
  src/assets/images/all-img/env-label.png
  src/assets/images/all-img/env-logo.png
  src/assets/images/all-img/env-title.png
  src/components/HeaderMain/index.vue
  src/views/main/environment.vue
Labels: 패키지, CSS, 스타일

#36 [CSS] 방송 등록 화면 스타일 수정
  src/components/Video/live.vue
  src/views/broadcast/live-register.vue
Labels: CSS

#38 [CSS] 로그인, 회원가입 페이지 및 상품 구매 컴포넌트
  src/assets/images/icon/essential.gif
  src/assets/images/svg/down.svg
  src/components/LiveBoard/liveboard-purchase.vue
  src/components/Modal/purchase-modal.vue
  src/views/broadcast/live-viewing.vue
  src/views/enterprise/join.vue
  src/views/enterprise/login.vue
  src/views/user/join-first.vue
  src/views/user/join.vue
Labels: 기능추가, CSS

#39 [CSS] 라이브보드 위치 조정 및 전체 버튼 모달 색상 변경
  src/assets/scss/components/_button.scss
  src/assets/scss/components/_table.scss
  src/components/LiveBoard/liveboard-product.vue
  src/components/LiveBoard/liveboard-sidebar.vue
  src/components/LiveBoard/liveboard-statistics.vue
  src/components/LiveBoard/liveboard-time.vue
  src/components/Modal/Modal.vue
  src/components/Modal/live-prepare-modal.vue
  src/components/liveboard/liveboard-chat.vue
  src/constant/live-product-data.js
  src/views/dashboard/broadcast-statistics.vue
  tailwind.config.js
Labels: CSS, 스타일

#40 [FEAT] 회원 정보 수정 페이지 및 페이지 링크 설정
  src/components/Card/product-card.vue
  src/components/LiveBoard/liveboard-purchase.vue
  src/components/Modal/purchase-modal.vue
  src/constant/data.js
  src/router/route.js
  src/views/broadcast/live-viewing.vue
  src/views/dashboard/user-info.vue
  src/views/mypage/edit-profile.vue
Labels: 기능추가, CSS, 리팩토링

#41 [CSS] 라이브 시청 페이지 디자인 수정
  src/components/LiveBoard/liveboard-broad.vue
  src/components/Video/live.vue
  src/components/Video/videoplayer.vue
  src/components/liveboard/liveboard-chat.vue
  src/views/broadcast/live-viewing.vue
Labels: CSS, 리팩토링

#42 [CSS] 라이브 준비 페이지 레이아웃 수정
  src/components/Card/product-card.vue
  src/components/Card/seller-broadcast-schedule.vue
  src/views/dashboard/live-prepare.vue
Labels: CSS

#43 [CSS] 방송 통계 디자인 수정 및 버튼 글씨 색상 적용
  src/components/LiveBoard/liveboard-product.vue
  src/components/Modal/Modal.vue
  src/views/broadcast/live-register.vue
  src/views/dashboard/broadcast-statistics.vue
Labels: CSS

#44 [FIX] 레이아웃 깨지는 문제 수정
  src/components/Video/live.vue
  src/components/Video/videoplayer.vue
  src/views/broadcast/live-viewing.vue
Labels: 버그 수정, CSS

#45 [FEAT] 나가기 버튼에 메인페이지 연결 추가, 화면 작을 시 스크롤 기능 추가
  src/views/broadcast/live-viewing.vue
  src/views/dashboard/live-prepare.vue
Labels: 기능추가, CSS

#46 [CSS] 방송 준비 페이지 카드 디자인 수정
  src/components/Card/product-card.vue
  src/components/Card/seller-broadcast-schedule.vue
  src/constant/appex-chart.js
Labels: CSS

#48 [CSS] 라이브 방송페이지 UI 수정
  src/components/Card/product-card.vue
  src/components/LiveBoard/liveboard-broad.vue
  src/components/LiveBoard/liveboard-purchase.vue
  src/components/Video/live.vue
  src/components/Video/videoplayer.vue
  src/components/liveboard/liveboard-chat.vue
  src/views/broadcast/live-viewing.vue
Labels: CSS, 리팩토링

#47 [CSS] 채팅 컴포넌트 디자인 수정
  src/components/LiveBoard/liveboard-time.vue
  src/components/liveboard/liveboard-chat.vue
Labels: 기능추가, CSS

#49 [CSS] 라이브 페이지 디자인
  package.json
  src/components/HeaderMain/index.vue
  src/components/LiveBoard/liveboard-broad.vue
  src/components/Video/live.vue
  src/components/Video/videoplayer.vue
  src/main.js
  src/router/route.js
  src/store/index.js
  src/views/broadcast/live-viewing.vue
  yarn.lock
Labels: CSS, 스타일

#50 [CHORE] : OpenVidu 의존성 추가
  package.json
  src/router/route.js
  src/views/test/OvVideo.vue
  src/views/test/UserVideo.vue
  src/views/test/test-openvidu.vue
  src/views/test/test-viewer.vue
  yarn.lock
Labels: 기능추가

#51 [CSS] 방송 일정 등록 UI 수정
  src/views/broadcast/live-register.vue
Labels: 기능추가, CSS

#52 [FEAT] 채팅 컴포넌트 기본 구현
  package.json
  src/components/UI/BaseSpinner.vue
  src/components/liveboard/liveboard-chat.vue
  src/main.js
  src/router/route.js
  src/store/chat.js
  src/store/index.js
  src/store/modules/user.js
  src/views/chat-view.vue
  vite.config.js
  yarn.lock
Labels: 기능추가

#53 [CSS] 상품 카테고리 페이지 연결 메뉴 삭제
  src/constant/data.js
Labels: CSS

#54 [FIX] 채팅 버그 수정
  package.json
  src/components/liveboard/liveboard-chat.vue
  src/store/modules/user.js
  yarn.lock
Labels: 버그 수정, 기능추가, CSS, 리팩토링, 스타일

#55 [FEAT] 유저 정보 및 채팅방 정보 구분 로직 추가
  src/Layout/main-index.vue
  src/components/liveboard/liveboard-chat.vue
  src/views/broadcast/live-viewing.vue
  src/views/broadcast/liveboard.vue
Labels: 기능추가

#56 [FEAT] 상점정보 조회 및 수정 백엔드 연결
  src/components/shop/shop-modify.vue
Labels: 버그 수정, 기능추가

#57 [FEAT] 채팅 컴포넌트 및 라이브뷰잉 페이지 디자인 수정 및 도배 방지 기능 추가
  src/components/liveboard/liveboard-chat.vue
  src/views/broadcast/live-viewing.vue
Labels: 버그 수정, 기능추가, CSS, 리팩토링

#58 [FEAT] 채팅 한줄 공지 추가
  src/components/Modal/index.vue
  src/components/liveboard/liveboard-chat.vue
Labels: 버그 수정, 기능추가, CSS

#59 [FEAT] 상품 목록 조회 백엔드 연결
  src/components/Product/product-list.vue
Labels: 기능추가, CSS

#61 [FEAT] 토스 결제 모듈
  package.json
  src/assets/images/logo/toss-logo.png
  src/assets/images/svg/arrow-bottom.svg
  src/assets/images/svg/arrow-right.svg
  src/assets/images/svg/check-before.svg
  src/assets/images/svg/check.svg
  src/assets/images/svg/etc.svg
  src/assets/images/svg/pay/bc.svg
  src/assets/images/svg/pay/hana.svg
  src/assets/images/svg/pay/hyundai.svg
  src/assets/images/svg/pay/kakaobank.svg
  src/assets/images/svg/pay/kakaopay.svg
  src/assets/images/svg/pay/kb.svg
  src/assets/images/svg/pay/kbank.svg
  src/assets/images/svg/pay/loca.svg
  src/assets/images/svg/pay/nh.svg
  src/assets/images/svg/pay/npay.svg
  src/assets/images/svg/pay/samsungcard.svg
  src/assets/images/svg/pay/samsungpay.svg
  src/assets/images/svg/pay/shinhan.svg
  src/assets/images/svg/pay/ssgpay.svg
  src/assets/images/svg/pay/tossbank.svg
  src/assets/images/svg/pay/tosspay.svg
  src/components/LiveBoard/liveboard-purchase.vue
  src/components/Modal/purchase-modal.vue
  src/components/Pay/FailView.vue
  src/components/Pay/SuccessView.vue
  src/components/Pay/style.css
  src/components/Pay/tosspayments-module.vue
  src/constant/confirmPayment.js
  src/router/route.js
  src/views/broadcast/live-viewing.vue
  yarn.lock
Labels: 기능추가, CSS

#62 [REFACTOR]: Merge 오류 해결
  src/views/broadcast/live-viewing.vue
Labels: 버그 수정, 리팩토링

#63 [FIX] 이미지 파일 깨짐 오류 수정
  index.html
  src/components/LiveBoard/liveboard-purchase.vue
  src/components/Pay/tosspayments-module.vue
  src/components/liveboard/liveboard-chat.vue
Labels: 버그 수정

#64 [REFACTOR] 안쓰는 의존성 삭제 및 코드구조 변경
  src/components/LiveBoard/liveboard-broad.vue
  src/views/broadcast/liveboard.vue
Labels: 리팩토링

#65 [FEAT] : 라이브 시작, 라이브 종료버튼 추가
  src/components/LiveBoard/liveboard-time.vue
Labels: 기능추가

#66 [FIX]: 주문 완료페이지 오류 수정
  package.json
  src/components/Pay/SuccessView.vue
  src/components/Pay/tosspayments-module.vue
  yarn.lock
Labels: 버그 수정

#67 [FEAT] 채팅 필터링 연결
  src/components/liveboard/liveboard-chat.vue
Labels: 기능추가, CSS, 스타일

#68 [FEAT] 입장 메시지 제거 및 알림
  src/components/liveboard/liveboard-chat.vue
Labels: 기능추가, CSS, 리팩토링

#69 [FEAT] 음소거 기능 추가, 방송중 장치 조작 기능 추가
  src/components/LiveBoard/liveboard-broad.vue
  src/components/LiveBoard/liveboard-sidebar.vue
  src/components/Modal/live-prepare-modal.vue
  src/components/Video/live.vue
  src/components/Video/videoplayer.vue
  src/views/broadcast/liveboard.vue
Labels: 기능추가

#70 [REFACTOR] 상품 목록 각 판매자별 조회 수정
  src/components/Product/product-list.vue
  src/components/shop/shop-modify.vue
  src/constant/data.js
Labels: 기능추가, 리팩토링, 스타일

#71 [FEAT] 메인 페이지 디자인 수정
  src/components/HeaderMain/date-tab.vue
  src/views/main/index.vue
  src/views/main/schedule.vue
Labels: CSS, 리팩토링

#72 [FEAT] 결제 검증 요청 구현
  src/components/Pay/SuccessView.vue
  src/components/Pay/tosspayments-module.vue
  src/constant/confirmPayment.js
Labels: 기능추가, 리팩토링

#74 [FEAT] 메인페이지 백엔드 연결
  src/components/Card/BroadcastCard.vue
  src/components/Category/Categories.vue
  src/components/Category/CategoryItem.vue
  src/views/main/index.vue
Labels: 버그 수정, 기능추가, CSS, 리팩토링

#73 [FEAT] 현재 시청자 수 확인기능 추가, 기타 버그 수정 및 주석 추가
  src/components/LiveBoard/liveboard-sidebar.vue
  src/components/LiveBoard/liveboard-statistics.vue
  src/components/LiveBoard/liveboard-time.vue
  src/components/Modal/live-prepare-modal.vue
  src/views/broadcast/liveboard.vue
Labels: 버그 수정, 기능추가, 스타일

#75 [FEAT] 상품 등록 기능 구현
  src/components/Product/product-list.vue
  src/constant/data.js
Labels: 버그 수정, 기능추가

#76 [FEAT] 구독, 일정표 페이지
  src/components/Card/schedule-card.vue
  src/components/HeaderMain/date-tab.vue
  src/router/index.js
  src/views/main/schedule.vue
Labels: 기능추가, CSS, 리팩토링

#77 [FEAT] 상품 정보 수정 연결
  src/components/Product/product-list.vue
Labels: 기능추가

#78 [FEAT] 라이브 보드 방송 통계 업데이트 로직 추가, 좋아요 수 업데이트 추가
  src/components/LiveBoard/liveboard-statistics.vue
  src/components/Video/live.vue
  src/views/broadcast/live-viewing.vue
Labels: 기능추가, 리팩토링

#79 [FEAT] 방송 등록하기 백엔드 연결
  src/views/broadcast/live-register.vue
Labels: 버그 수정, 기능추가, CSS, 스타일

#80 [FEAT] 채널 판매 상품 삭제 연결
  src/components/Product/product-list.vue
Labels: 기능추가

#81 [CSS] 스켈레톤 및 기타 디자인 수정
  src/components/Card/BroadcastCard.vue
  src/components/Card/schedule-card.vue
  src/components/HeaderMain/date-tab.vue
  src/components/Skeleton/Main-Carou-skeleton.vue
  src/components/Skeleton/Main-chance-skeleton.vue
  src/components/Skeleton/Main-scheduled-skeleton.vue
  src/components/Skeleton/Schedule-skeleton.vue
  src/views/main/index.vue
  src/views/main/schedule.vue
Labels: 버그 수정, 기능추가, CSS, 리팩토링, 스타일

#83 [FEAT] 최고 시청자 수, 평균 시청자 수 집계 기능 추가, 방송 통계 정보 서버에 전달 기능 추가
  src/components/LiveBoard/liveboard-statistics.vue
  src/components/LiveBoard/liveboard-time.vue
  src/views/broadcast/liveboard.vue
Labels: 기능추가

#84 [FEAT] 방송 예정 백엔드 연결
  src/components/Card/product-card.vue
  src/components/Card/seller-broadcast-schedule.vue
  src/views/broadcast/live-register.vue
  src/views/dashboard/live-prepare.vue
Labels: 기능추가, CSS, 스타일

#86 [FEAT] 주문 내역 조회 연결
  src/components/Order/order-list.vue
  src/components/Order/review-list.vue
  src/views/mypage/order-list.vue
Labels: 기능추가

#85 [CSS] 디자인 세부 수정
  src/views/main/environment.vue
  src/views/main/index.vue
Labels: CSS

#87 [REFACTOR] 이미지 조회 및 표시 로직 변경
  src/components/Card/BroadcastCard.vue
  src/components/Card/schedule-card.vue
  src/views/main/index.vue
Labels: 리팩토링

#88 [REFACTOR] 상품 등록, 수정 이미지 업로드 로직 변경
  src/components/Product/product-list.vue
Labels: 리팩토링

#89 [FEAT] 메인 슬라이드 방송 연결
  src/views/main/index.vue
Labels: 기능추가

#90 [FEAT] 누적 시청자 수 서버 통신 추가
  src/views/broadcast/live-viewing.vue
Labels: 기능추가

#91 [FEAT] 브랜드페이 결제수단 등록
  src/components/Pay/brandpay-register.vue
  src/components/Pay/brandpay-successUrl
  src/components/Pay/callback-auth.vue
  src/components/Pay/tosspayments-brandpay-module.vue
  src/constant/data.js
  src/router/route.js
Labels: 기능추가

#92 [CSS] 텍스트 넘치는 문제 수정
  src/components/Card/BroadcastCard.vue
  src/views/main/index.vue
Labels: CSS

#93 [ FEAT] 방송 등록 시 할인가 단위 조정 구현
  src/components/Card/product-card.vue
  src/router/route.js
  src/views/broadcast/live-prepare.vue
  src/views/broadcast/live-register.vue
Labels: 버그 수정, 기능추가, 문서

#94 [FEAT] 상품 통계 및 메인페이지 수정
  src/components/Card/BroadcastCard.vue
  src/components/Card/product-statistics-card.vue
  src/components/Table/statistics-default-table.vue
  src/views/dashboard/product-statistics.vue
  src/views/main/index.vue
  src/views/main/schedule.vue
Labels: 기능추가, CSS

#95 [REFACTOR] 상점 정보 수정 이미지 로직 수정
  src/components/Order/order-list.vue
  src/components/Product/product-list.vue
  src/components/shop/shop-modify.vue
  src/views/mypage/order-list.vue
Labels: 버그 수정, 리팩토링

#96 [FEAT] 브랜드페이 결제 수단 조회 및 결제 방법 선택
  src/components/LiveBoard/liveboard-purchase.vue
  src/components/Pay/brandpay-fail.vue
  src/components/Pay/brandpay-register.vue
  src/components/Pay/brandpay-success.vue
  src/components/Pay/brandpay-successUrl
  src/components/Pay/callback-auth.vue
  src/components/Pay/tosspayments-brandpay-module.vue
  src/components/Pay/tosspayments-module.vue
  src/router/route.js
Labels: 기능추가

#97 [REFACTOR] 주문 내역 상품 이미지 로직 수정
  src/components/Order/order-list.vue
  src/components/Order/review-list.vue
  src/views/mypage/order-list.vue
Labels: CSS, 리팩토링

#99 [FEAT] footer, lottie, chatbot 구현
  package.json
  src/assets/images/all-img/penguinLottie.json
  src/components/Chatbot/AIChatBot.vue
  src/components/Footer/CustomFooter.vue
  src/components/HeaderMain/index.vue
  src/components/UI/LottieAnimation.vue
  src/views/main/index.vue
  src/views/main/schedule.vue
  yarn.lock
Labels: 기능추가, CSS, 리팩토링

#98 [FEAT] 통계 데이터 바인딩
  src/views/dashboard/broadcast-statistics.vue
Labels: 기능추가

#100 [FEAT] 라이브보드, 시청화면 방송 기본정보 백엔드 연결
  src/components/LiveBoard/liveboard-broad.vue
  src/components/LiveBoard/liveboard-sidebar.vue
  src/components/LiveBoard/liveboard-time.vue
  src/components/Video/live.vue
  src/views/broadcast/live-viewing.vue
  src/views/broadcast/liveboard.vue
Labels: 버그 수정, 기능추가, CSS, 리팩토링

#101 [FEAT] 리뷰 등록 및 삭제 연결
  src/components/Order/order-list.vue
  src/components/Order/review-list.vue
  src/views/mypage/order-list.vue
Labels: 기능추가, 테스트

#102 [FIX] 상품,상점 이미지 불러오기 로직 수정
  src/components/Product/product-list.vue
  src/components/shop/shop-modify.vue
Labels: 버그 수정, CSS

#104 [FEAT] OpneAI API 챗봇
  src/components/Chatbot/AIChatBot.vue
  src/components/Chatbot/Broadcast.vue
  src/components/Chatbot/OrderHistory.vue
  src/components/Chatbot/Profile.vue
  src/components/Chatbot/Refund.vue
  src/views/main/index.vue
Labels: 기능추가, 패키지, CSS, 리팩토링

#103 [FEAT] : 평균 시청시간 계산기능 추가
  src/components/Video/live.vue
  src/views/broadcast/live-viewing.vue
  src/views/broadcast/liveboard.vue
Labels: 기능추가

#105 [FEAT] 최근 본 방송 목록 연결
  src/components/Card/broadcast-historyCard.vue
  src/components/Order/review-list.vue
  src/views/mypage/broadcast-history.vue
Labels: 기능추가, 스타일

#108 [FEAT] 최근 방송 시청 기록, 채널명, 채널이미지 추가
  src/components/Card/broadcast-historyCard.vue
  src/components/shop/shop-modify.vue
  src/views/mypage/broadcast-history.vue
Labels: 기능추가, CSS

#107 [FEAT] 주문 객체 생성 및 리팩토링
  src/components/LiveBoard/liveboard-purchase.vue
  src/components/Modal/purchase-modal.vue
  src/components/Pay/SuccessView.vue
  src/components/Pay/brandpay-register.vue
  src/components/Pay/brandpay-success.vue
  src/components/Pay/tosspayments-module.vue
  src/router/route.js
  src/store/index.js
  src/store/modules/order.js
  src/views/broadcast/live-viewing.vue
Labels: 버그 수정, 기능추가, 리팩토링

#109 [FEAT] 챗봇 브랜드페이, 최근시청내역 조회
  src/components/Chatbot/AIChatBot.vue
  src/components/Chatbot/Payment.vue
  src/components/Chatbot/RecentViewedBroadcasts.vue
  src/views/main/schedule.vue
Labels: 기능추가, CSS

#110 [CSS] 챗봇 카드 표시 css수정
  src/components/Chatbot/AIChatBot.vue
  src/components/Chatbot/Payment.vue
Labels: CSS

#111 [FEAT] 시간대 별 시청자 수 표 추가
  src/views/dashboard/broadcast-statistics.vue
Labels: 기능추가

#112 [FEAT] 리뷰통계 상품 목록 및 정보 조회
  src/views/dashboard/review-statistics.vue
Labels: 기능추가

#113 [FEAT] 라이브보드, 시청화면 방송 판매 상품 연결
  src/components/Card/product-card.vue
  src/components/LiveBoard/liveboard-product.vue
  src/constant/live-product-data.js
  src/views/broadcast/live-viewing.vue
  src/views/broadcast/liveboard.vue
Labels: 버그 수정, 기능추가, CSS, 리팩토링, 스타일

#114 [FEAT] 리뷰 유해성 검사 추가
  src/components/Order/order-list.vue
Labels: 기능추가, CSS

#115 [FIX] 방송 시청 화면 로딩 에러 해결
  src/views/broadcast/live-viewing.vue
Labels: 버그 수정

#116 [FIX] 리뷰 등록시 리뷰 확인 즉시 안되는 현상 수정
  src/components/Order/order-list.vue
  src/views/mypage/order-list.vue
Labels: 버그 수정

#117 [FIX] 라이브 시작 에러 해결
  src/views/broadcast/liveboard.vue
Labels: 버그 수정

#118 [REFACTOR] 테이블 변경에 따른 필요없는 코드 주석처리
  src/views/broadcast/live-viewing.vue
  src/views/broadcast/liveboard.vue
Labels: 리팩토링

#120 [FEAT] 리뷰 내용 의미망 분석
  src/components/Table/statistics-review-product-table.vue
  src/components/reivew/reviewchart.vue
  src/views/dashboard/review-statistics.vue
Labels: 기능추가, CSS, 리팩토링

#121 [FEAT] 일반회원가입
  package.json
  src/components/Checkbox/index.vue
  src/components/Map/map.vue
  src/router/route.js
  src/views/user/join.vue
  yarn.lock
Labels: 기능추가

#122 [FEAT] 상품별 리뷰 및 리뷰 내용 요약 조회
  src/views/dashboard/review-statistics.vue
Labels: 기능추가

#123 [FEAT] 라이브보드 공지, 자주묻는 질문 등록 및 삭제 백엔드 연결
  src/components/LiveBoard/liveboard-sidebar.vue
  src/components/LiveBoard/liveboard-statistics.vue
  src/views/broadcast/liveboard.vue
Labels: 기능추가, CSS, 스타일

#124 [FEAT]리뷰 핵심 문구 차트
  src/components/reivew/reviewchart.vue
  src/views/dashboard/review-statistics.vue
Labels: 버그 수정, 기능추가, CSS, 리팩토링, 스타일

#126 [FEAT] 휴대폰번호 인증 및 회원가입 폼 검증
  src/components/LiveBoard/liveboard-purchase.vue
  src/components/Modal/purchase-modal.vue
  src/components/Pay/tosspayments-module.vue
  src/views/user/join.vue
Labels: 기능추가, CSS

#127 [FIX] 채팅방 동적 분리
  src/views/broadcast/live-viewing.vue
  src/views/broadcast/liveboard.vue
Labels: 버그 수정, 리팩토링

#128 [FEAT] 시청화면 공지, faq 백엔드 연결
  src/views/broadcast/live-viewing.vue
Labels: 기능추가

#129 [REFACTOR] 크롬 자동 재생 정책 우회
  src/components/LiveBoard/liveboard-broad.vue
  src/components/Video/videoplayer.vue
Labels: 리팩토링

#130 [FEAT] 리뷰통계 감정분석 데이터 바인딩
  src/components/Table/statistics-review-product-table.vue
  src/components/reivew/reviewchart.vue
  src/views/dashboard/review-statistics.vue
Labels: 버그 수정, 기능추가, CSS, 리팩토링

#131 [FEAT] 프롬프트 AI 도입
  src/components/LiveBoard/liveboard-prompt.vue
  src/views/broadcast/liveboard.vue
Labels: 버그 수정, 기능추가, CSS, 리팩토링

#132 [FEAT] 방송 시작, 종료시간 백엔드 연결
  src/components/LiveBoard/liveboard-time.vue
  src/views/broadcast/live-viewing.vue
Labels: 기능추가, CSS

#133 [FEAT] 구매페이지 내 리뷰 내용 및 요약 연결
  src/components/LiveBoard/liveboard-purchase.vue
Labels: 기능추가

#134 [FEAT] 구독 관리 페이지
  src/components/Subscription/subscription-channel.vue
  src/router/route.js
  src/views/mypage/subscription-settings.vue
Labels: 기능추가, CSS

#135 [CSS] 라이브보드 스타일 조정
  src/components/LiveBoard/liveboard-product.vue
  src/components/LiveBoard/liveboard-prompt.vue
  src/components/LiveBoard/liveboard-sidebar.vue
  src/components/LiveBoard/liveboard-statistics.vue
  src/components/LiveBoard/liveboard-time.vue
  src/views/broadcast/liveboard.vue
Labels: CSS, 스타일

#136 [FEAT] 로그인
  src/views/user/login.vue
  vite.config.js
Labels: 기능추가

#139 [REVERT] 깃 과거로 Revert
  .eslintrc.js
  .github/workflows/main.yaml
  src/Layout/index.vue
  src/Layout/main-index.vue
  src/Layout/user-index.vue
  src/components/Footer/CustomFooter.vue
  src/components/Footer/FooterMenu.vue
  src/components/Footer/index.vue
  src/components/LiveBoard/liveboard-purchase.vue
  src/components/liveboard/liveboard-broad.vue
  src/components/liveboard/liveboard-product.vue
  src/components/liveboard/liveboard-prompt.vue
  src/components/liveboard/liveboard-purchase.vue
  src/components/liveboard/liveboard-sidebar.vue
  src/components/liveboard/liveboard-statistics.vue
  src/components/liveboard/liveboard-time.vue
  src/router/route.js
  src/views/broadcast/live-viewing.vue
  src/views/broadcast/liveboard.vue
  src/views/enterprise/login.vue
  src/views/user/login.vue
  vite.config.js
Labels: 버그 수정

#140 [Fix] LiveBoard 폴더 liveboard 폴더 통합
  src/components/liveboard/liveboard-broad.vue
  src/components/liveboard/liveboard-product.vue
  src/components/liveboard/liveboard-prompt.vue
  src/components/liveboard/liveboard-purchase.vue
  src/components/liveboard/liveboard-sidebar.vue
  src/components/liveboard/liveboard-statistics.vue
  src/components/liveboard/liveboard-time.vue
  src/views/broadcast/live-viewing.vue
  src/views/broadcast/liveboard.vue
Labels: 버그 수정

#141 [FEAT] 자동 배포 빌드 파일 추가 및 오류나는 코드 주석처리 및 삭제
  .github/workflows/yarn.yaml
  src/components/Accordion/index.vue
  src/components/Alert/index.vue
  src/components/Badge/index.vue
  src/components/Breadcrumbs/Breadcrumbs2.vue
  src/components/Breadcrumbs/index.vue
  src/components/Button/index.vue
  src/components/Card/analytics-card.vue
  src/components/Chatbot/AIChatBot.vue
  src/components/Dropdown/SplitDropdown.vue
  src/components/Dropdown/index.vue
  src/components/Footer/CustomFooter.vue
  src/components/Footer/FooterMenu.vue
  src/components/Header/Navtools/HandleMobileMenu.vue
  src/components/Header/Navtools/Message.vue
  src/components/Header/Navtools/MonochromeMode.vue
  src/components/Header/Navtools/Notification.vue
  src/components/Header/Navtools/Profile.vue
  src/components/Header/Navtools/SearchModal.vue
  src/components/Header/Navtools/SwitchDark.vue
  src/components/HeaderMain/Navtools/HandleMobileMenu.vue
  src/components/HeaderMain/Navtools/Message.vue
  src/components/HeaderMain/Navtools/MonochromeMode.vue
  src/components/HeaderMain/Navtools/Notification.vue
  src/components/HeaderMain/Navtools/Profile.vue
  src/components/HeaderMain/Navtools/SearchModal.vue
  src/components/HeaderMain/Navtools/SwitchDark.vue
  src/components/InputGroup/index.vue
  src/components/Modal/Modal.vue
  src/components/Modal/index.vue
  src/components/Pagination/index.vue
  src/components/Product/product-list.vue
  src/components/Select/VueSelect.vue
  src/components/Switch/index.vue
  src/components/Textarea/index.vue
  src/components/Textinput/index.vue
  src/components/liveboard/liveboard-chat.vue
  src/components/liveboard/liveboard-product.vue
  src/components/liveboard/liveboard-sidebar.vue
  src/components/liveboard/liveboard-statistics.vue
  src/components/liveboard/liveboard-time.vue
  src/router/route.js
  src/views/broadcast/live-register.vue
  src/views/enterprise/login.vue
  src/views/main/index.vue
  src/views/main/schedule.vue
  src/views/user/login.vue
Labels: 기능추가, 스타일

#143 [FIX] 배포환경에서 방송 에러 의심 코드 수정
  src/views/broadcast/live-viewing.vue
  src/views/broadcast/liveboard.vue
Labels: 버그 수정

#142 [FIX] 이미지 파일 웹 url 전환
  src/components/Category/Categories.vue
  src/components/Chatbot/AIChatBot.vue
  src/components/UI/LottieAnimation.vue
  src/views/main/index.vue
  src/views/main/schedule.vue
Labels: 버그 수정, CSS

#144 [FIX] 채팅 엔드포인트 수정
  src/components/liveboard/liveboard-chat.vue
Labels: 버그 수정

#145 [FEAT] 실시간 방송 상품 상태 백엔드 연결
  src/components/liveboard/liveboard-product.vue
  src/components/liveboard/liveboard-statistics.vue
  src/views/broadcast/liveboard.vue
Labels: 기능추가, CSS

#146 [FIX] 채팅 url수정
  src/components/liveboard/liveboard-chat.vue
Labels: 버그 수정

#149 [FEAT] .env파일 gitignore 추가
  .gitignore
Labels: 기능추가

#150 [CSS] 메인페이지 가격 포맷팅
  src/views/main/index.vue
Labels: CSS

#151 [FEAT] 실시간 자막 기능 추가
  src/components/Video/videoplayer.vue
  src/views/broadcast/liveboard.vue
Labels: 기능추가

#154 [FEAT] 환경 인증 상품 등록 및 목록 조회
  src/components/Product/product-list.vue
Labels: 버그 수정, 기능추가

#152 [FEAT] 금칙어 추가
  src/components/liveboard/liveboard-chat.vue
Labels: 기능추가, CSS

#153 [FEAT] 실시간 방송 종료 SSE 백엔드 연결
  src/components/liveboard/liveboard-time.vue
  src/views/broadcast/live-viewing.vue
Labels: 기능추가, CSS

#155 [FEAT] 유저 방송 시청 기록 저장 백엔드 연결
  src/views/broadcast/live-viewing.vue
Labels: 버그 수정, 기능추가, CSS

#157 [CSS] 방송 화면 크기, 자막 활성/비활성화 추가
  src/components/Video/live.vue
  src/components/Video/videoplayer.vue
Labels: CSS

#158 [FEAT] 로그인 상태 관리, 사용자 정보 수정 및 uuid 바인딩
  package.json
  src/assets/images/users/default-img.png
  src/axios.js
  src/components/Card/broadcast-historyCard.vue
  src/components/Chatbot/OrderHistory.vue
  src/components/Chatbot/RecentViewedBroadcasts.vue
  src/components/Header/Navtools/Profile.vue
  src/components/HeaderMain/Navtools/Profile.vue
  src/components/Modal/purchase-modal.vue
  src/components/Order/order-list.vue
  src/components/Order/review-list.vue
  src/store/index.js
  src/store/modules/auth.js
  src/store/modules/order.js
  src/store/modules/user.js
  src/views/broadcast/live-viewing.vue
  src/views/mypage/broadcast-history.vue
  src/views/mypage/edit-profile.vue
  src/views/mypage/order-list.vue
  src/views/user/join.vue
  src/views/user/login.vue
  yarn.lock
Labels: 버그 수정, 기능추가, CSS, 리팩토링

#159 [FIX] 상품 정보 수정 이미지 미리보기 및 이미지 수정
  src/components/Product/product-list.vue
Labels: 버그 수정

#160 [FIX] Security Cors 버그 수정
  src/views/mypage/edit-profile.vue
  src/views/user/login.vue
  vite.config.js
Labels: 버그 수정

#162 [FIX] 상품 등록, 수정 모달 버그 수정
  src/components/Product/product-list.vue
Labels: 버그 수정

#163 [FIX] 병합 후 각종 버그 수정
  src/components/Category/Categories.vue
  src/components/Chatbot/AIChatBot.vue
  src/components/Chatbot/Broadcast.vue
  src/components/Chatbot/OrderHistory.vue
  src/components/Chatbot/RecentViewedBroadcasts.vue
  src/components/liveboard/liveboard-chat.vue
  src/components/liveboard/liveboard-prompt.vue
  src/views/main/index.vue
  src/views/main/schedule.vue
Labels: 버그 수정, CSS, 리팩토링

#164 [FIX] 각종 버그 수정 및 좋아요 로직 변경
  src/components/Video/live.vue
  src/components/Video/videoplayer.vue
  src/views/broadcast/live-viewing.vue
  src/views/broadcast/liveboard.vue
  src/views/dashboard/broadcast-statistics.vue
Labels: 버그 수정, 기능추가, CSS, 리팩토링, 스타일

#165 [FIX] 방송 등록하기 예외처리 추가 및 세부 디자인 변경
  src/components/liveboard/liveboard-product.vue
  src/components/liveboard/liveboard-time.vue
  src/views/broadcast/live-register.vue
  src/views/broadcast/liveboard.vue
Labels: 버그 수정, 기능추가, CSS

#168 [FIX] uuid 바인딩 수정
  src/components/Pay/brandpay-register.vue
  src/views/enterprise/login.vue
Labels: 버그 수정

#169 [FIX] 결제창 svg 깨짐 수정
  src/components/Order/order-list.vue
  src/components/Order/review-list.vue
  src/components/Pay/brandpay-register.vue
  src/components/Pay/tosspayments-module.vue
  src/views/enterprise/join.vue
  src/views/enterprise/login.vue
Labels: 버그 수정

#170 [FEAT] 사업자 등록 인증 구현
  src/views/enterprise/join.vue
Labels: 기능추가, CSS

#171 [ REFACTOR] 실시간 라이브 준비 백엔드 연결
  src/components/Card/seller-broadcast-schedule.vue
  src/components/Video/live.vue
  src/components/liveboard/liveboard-broad.vue
  src/components/liveboard/liveboard-chat.vue
  src/components/liveboard/liveboard-time.vue
  src/views/broadcast/live-prepare.vue
  src/views/broadcast/live-register.vue
  src/views/broadcast/live-viewing.vue
  src/views/broadcast/liveboard.vue
Labels: 버그 수정, CSS, 리팩토링, 스타일

#172 [REFACOTR] 시청화면 SSE 구독 요청 주기 설정
  src/views/broadcast/live-register.vue
  src/views/broadcast/live-viewing.vue
Labels: 버그 수정, 리팩토링

#175 [FIX] 시청자 수 기록기능 복구
  src/components/liveboard/liveboard-statistics.vue
Labels: 버그 수정

#176 [FIX] 좋아요 체크 제대로 못하는 문제 수정
  src/components/Video/live.vue
  src/components/liveboard/liveboard-statistics.vue
Labels: 버그 수정

#177 [FIX] 브렌드페이 로딩 URL
  src/components/Chatbot/Profile.vue
  src/components/Header/Navtools/Profile.vue
  src/components/HeaderMain/Navtools/Profile.vue
  src/components/Pay/brandpay-register.vue
  src/components/Product/product-list.vue
  src/components/Video/live.vue
  src/router/index.js
  src/router/route.js
  src/store/modules/auth.js
  src/views/enterprise/join.vue
  src/views/mypage/edit-profile.vue
  src/views/user/join.vue
  src/views/user/login.vue
Labels: 버그 수정, 테스트

#178 [FIX] 방송 예정 목록 시간 수정
  src/components/Card/seller-broadcast-schedule.vue
  src/components/Sidebar/index.vue
  src/router/route.js
Labels: 버그 수정, 패키지

#179 [FIX] 주문창 디자인 수정
  src/components/Header/Navtools/Profile.vue
  src/components/HeaderMain/Navtools/Profile.vue
  src/components/Pay/style.css
  src/components/Pay/tosspayments-module.vue
  src/components/liveboard/liveboard-purchase.vue
Labels: 버그 수정, CSS

#180 [FIX] 라이브 등록 후 경로 수정
  src/views/broadcast/live-register.vue
Labels: 버그 수정

#181 [STYLE] 상품 상세페이지 수정
  src/views/broadcast/live-viewing.vue
  src/views/mypage/edit-profile.vue
Labels: CSS

#182 [FEAT] 자막 번역 기능 추가
  src/components/Video/live.vue
  src/components/Video/videoplayer.vue
  src/views/broadcast/liveboard.vue
Labels: 기능추가, CSS

#183 [STYLE] 판매자 회원가입 양식 수정
  src/views/enterprise/join.vue
Labels: 스타일

#185 [FIX] 날짜 범위 방송 목록 가져오지 못하는 오류 수정
  src/views/dashboard/broadcast-statistics.vue
Labels: 버그 수정

#187 [FIX] 좋아요 수정
  src/components/Card/schedule-card.vue
  src/components/Card/seller-broadcast-schedule.vue
  src/components/Chatbot/AIChatBot.vue
  src/components/Chatbot/Broadcast.vue
  src/components/Chatbot/OrderHistory.vue
  src/components/Chatbot/RecentViewedBroadcasts.vue
  src/components/Chatbot/Refund.vue
  src/components/Header/Navtools/Profile.vue
  src/components/HeaderMain/Navtools/Profile.vue
  src/components/Modal/live-prepare-modal.vue
  src/components/Modal/purchase-modal.vue
  src/components/Order/order-list.vue
  src/components/Order/review-list.vue
  src/components/Pay/SuccessView.vue
  src/components/Pay/brandpay-register.vue
  src/components/Pay/brandpay-success.vue
  src/components/Pay/tosspayments-module.vue
  src/components/Product/product-list.vue
  src/components/Subscription/subscription-channel.vue
  src/components/UI/LottieAnimation.vue
  src/components/Video/live.vue
  src/components/Video/videoplayer.vue
  src/components/liveboard/liveboard-chat.vue
  src/components/liveboard/liveboard-product.vue
  src/components/liveboard/liveboard-prompt.vue
  src/components/liveboard/liveboard-purchase.vue
  src/components/liveboard/liveboard-sidebar.vue
  src/components/liveboard/liveboard-statistics.vue
  src/components/liveboard/liveboard-time.vue
  src/components/shop/shop-modify.vue
  src/store/modules/auth.js
  src/store/modules/order.js
  src/store/todo.js
  src/views/broadcast/live-prepare.vue
  src/views/broadcast/live-register.vue
  src/views/broadcast/live-viewing.vue
  src/views/broadcast/liveboard.vue
  src/views/chat-view.vue
  src/views/dashboard/broadcast-statistics.vue
  src/views/dashboard/product-statistics.vue
  src/views/dashboard/review-statistics.vue
  src/views/enterprise/join.vue
  src/views/enterprise/login.vue
  src/views/main/index.vue
  src/views/main/schedule.vue
  src/views/mypage/broadcast-history.vue
  src/views/mypage/edit-profile.vue
  src/views/mypage/order-list.vue
  src/views/user/join.vue
  src/views/user/login.vue
Labels: 버그 수정, 스타일
