Repository SUSUSSG/PenGreenLiveFrontEnd, pull requests merged in 2024-04, with the labels that each got.

#1 [CHORE] Views 패키지 구조 추가
  README.md
  src/views/broadcast/README.md
  src/views/dashboard/README.md
  src/views/main/README.md
  src/views/mypage/README.md
  src/views/user/README.md
Labels: 패키지

#3 [FEAT] 헤더 및 페이지 추가
  src/Layout/main-index.vue
  src/assets/images/logo/pengreenlive-logo-dark.png
  src/assets/images/logo/pengreenlive-logo-white.png
  src/components/Header/main-index.vue
  src/components/HeaderMain/Navtools/DesktopMenu.vue
  src/components/HeaderMain/Navtools/HandleMobileMenu.vue
  src/components/HeaderMain/Navtools/Language.vue
  src/components/HeaderMain/Navtools/Logo.vue
  src/components/HeaderMain/Navtools/Message.vue
  src/components/HeaderMain/Navtools/MobileLogo.vue
  src/components/HeaderMain/Navtools/MonochromeMode.vue
  src/components/HeaderMain/Navtools/Notification.vue
  src/components/HeaderMain/Navtools/Profile.vue
  src/components/HeaderMain/Navtools/SearchModal.vue
  src/components/HeaderMain/Navtools/SwitchDark.vue
  src/components/HeaderMain/horizental-nav.vue
  src/components/HeaderMain/index.vue
  src/router/route.js
  src/views/main/index.vue
Labels: 기능추가, CSS

#4 [FEAT] 방송준비모달, 방송등록 페이지 추가
  src/assets/images/all-img/no-image.png
  src/components/Modal/live-prepare-modal.vue
  src/components/Sidebar/index.vue
  src/router/route.js
  src/views/broadcast/live-register.vue
Labels: 기능추가, CSS, 리팩토링, 스타일

#5 [FEAT] 메인 페이지(첫 화면 작업)
  src/Layout/main-index.vue
  src/components/Card/BroadcastCard.vue
  src/components/Category/Categories.vue
  src/components/Category/CategoryItem.vue
  src/views/main/index.vue
Labels: 기능추가, CSS

#6 [FEAT] 상품 관리 기능 구현
  package-lock.json
  src/assets/images/all-img/logo1.png
  src/assets/images/all-img/logo2.png
  src/assets/images/all-img/logo3.png
  src/components/Modal/Modal.vue
  src/components/Product/product-list.vue
  src/constant/basic-tablle-data.js
  src/views/dashboard/index.vue
Labels: 기능추가, CSS, 리팩토링, 문서

#7 [FEAT] 채팅 컴포넌트 추가
  src/components/liveboard/liveboard-chat.vue
Labels: 기능추가, CSS

#9 [FEAT] 사용자 로그인 및 회원가입 페이지 UX
  src/assets/images/logo/kakao-logo.png
  src/assets/images/logo/naver-logo.png
  src/router/route.js
  src/views/enterprise/join.vue
  src/views/enterprise/login.vue
  src/views/user/join-first.vue
  src/views/user/join.vue
  src/views/user/login.vue
Labels: 기능추가

#10 [FEAT] 판매자 라이브보드 기본 UX
  src/assets/images/all-img/now.png
  src/components/LiveBoard/liveboard-broad.vue
  src/components/LiveBoard/liveboard-product.vue
  src/components/LiveBoard/liveboard-prompt.vue
  src/components/LiveBoard/liveboard-sidebar.vue
  src/components/LiveBoard/liveboard-statistics.vue
  src/components/LiveBoard/liveboard-time.vue
  src/constant/live-product-data.js
  src/router/route.js
  src/views/broadcast/liveboard.vue
  src/views/index.vue
Labels: 기능추가, CSS, 스타일

#11 [FEAT] 메인페이지 css 수정
  index.html
  src/views/main/index.vue
Labels: 버그 수정, 기능추가, CSS, 리팩토링, 스타일

#12 [FEAT] 상점 정보 입력 및 상품 카테고리 설정 페이지 추가
  src/components/Product/product-category.vue
  src/components/shop/shop-modify.vue
  src/constant/basic-tablle-data.js
  src/router/route.js
  src/store/todo.js
  src/views/broadcast/live-register.vue
  src/views/dashboard/product-category.vue
  src/views/dashboard/product-list.vue
  src/views/dashboard/shop-modify.vue
Labels: 기능추가, CSS, 리팩토링, 스타일

#13 [FEAT] 메인페이지 및 일정표 페이지
  src/Layout/index.vue
  src/Layout/main-index.vue
  src/components/Card/schedule-card.vue
  src/components/Category/Categories.vue
  src/components/Category/CategoryItem.vue
  src/components/Header/main-index.vue
  src/components/HeaderMain/index.vue
  src/router/route.js
  src/views/main/index.vue
  src/views/main/schedule.vue
Labels: 버그 수정, 기능추가, CSS, 리팩토링, 스타일

#15 [Refactor] 방송 플레이어 컴포넌트 분리
  src/components/Video/live.vue
  src/components/Video/videoplayer.vue
  src/views/broadcast/live-viewing.vue
  src/views/main/index.vue
Labels: 기능추가, 리팩토링, 스타일

#16 [FEAT] 회원가입 진입 페이지 및 페이지 연결
  src/router/route.js
  src/views/enterprise/login.vue
  src/views/user/join-first.vue
Labels: 기능추가

#17 [FEAT] 메뉴 헤더 추가 및 디자인 수정 등
  src/Layout/index.vue
  src/Layout/main-index.vue
  src/assets/images/all-img/category-icon/icon-all.png
  src/assets/images/all-img/category-icon/icon-cosmetic.png
  src/assets/images/all-img/category-icon/icon-furniture.png
  src/assets/images/all-img/category-icon/icon-hoodie.png
  src/assets/images/all-img/category-icon/icon-kids.png
  src/assets/images/all-img/category-icon/icon-organic-food.png
  src/assets/images/all-img/category-icon/icon-tech.png
  src/components/Category/Categories.vue
  src/components/Category/CategoryItem.vue
  src/components/HeaderMain/Navtools/Profile.vue
  src/components/HeaderMain/menu-header-nav.vue
  src/router/route.js
  src/views/main/environment.vue
  src/views/main/index.vue
  src/views/main/schedule.vue
Labels: 기능추가, CSS, 리팩토링, 스타일

#18 [CONFLICT] 라우트 충돌 문제 수정
  src/router/route.js
Labels: 버그 수정

#21 [FEAT] 일정 바 추가 및 디자인 수정
  favicon.svg
  index.html
  loader.css
  src/components/Button/ScrollTopButton.vue
  src/components/Category/Categories.vue
  src/components/Category/CategoryItem.vue
  src/components/HeaderMain/date-tab.vue
  src/components/HeaderMain/menu-header-nav.vue
  src/router/index.js
  src/views/main/environment.vue
  src/views/main/index.vue
  src/views/main/schedule.vue
Labels: 기능추가, CSS, 문서

#19 [FEAT] 라이브 정보 보기 탭 추가, 상품 카드 컴포넌트 추가
  src/components/Card/product-card.vue
  src/components/Video/live.vue
  src/components/liveboard/liveboard-chat.vue
  src/views/broadcast/live-viewing.vue
Labels: 기능추가, CSS

#22 [FEAT] 주문내역 및 리뷰작성 페이지 추가
  src/Layout/user-index.vue
  src/assets/scss/components/_table.scss
  src/components/Order/order-list.vue
  src/components/Order/review-list.vue
  src/constant/data.js
  src/router/route.js
  src/views/mypage/order-list.vue
Labels: 기능추가, CSS, 리팩토링

#20 [FEAT] 판매자 라이브보드 모달 구현
  src/components/LiveBoard/liveboard-broad.vue
  src/components/LiveBoard/liveboard-product.vue
  src/components/LiveBoard/liveboard-prompt.vue
  src/components/LiveBoard/liveboard-sidebar.vue
  src/components/Modal/live-prepare-modal.vue
  src/components/liveboard/liveboard-chat.vue
  src/constant/live-product-data.js
  src/views/broadcast/liveboard.vue
Labels: 기능추가, CSS, 스타일

#23 [FEAT] 라이브 상품 구매 페이지
  src/assets/images/all-img/product-explain-sample.jpg
  src/assets/images/all-img/product-sample.jpg
  src/components/LiveBoard/liveboard-purchase.vue
  src/views/broadcast/live-viewing.vue
  src/views/enterprise/join.vue
  src/views/user/join.vue
Labels: 기능추가

#24 [REFACTOR] 라우터 수정
  src/router/route.js
  src/views/main/index.vue
Labels: 버그 수정, 리팩토링

#26 [FEAT] 최근 방송 시청 기록 페이지 추가
  src/components/Card/broadcast-historyCard.vue
  src/router/route.js
  src/views/mypage/broadcast-history.vue
Labels: 기능추가, CSS

#25 [FEAT] 통계 카드 컴포넌트 구현
  src/components/Card/analytics-card.vue
  src/router/route.js
  src/views/dashboard/broadcast-statistics.vue
  src/views/dashboard/product-statistics.vue
  src/views/dashboard/review-statistics.vue
  src/views/main/schedule.vue
Labels: 기능추가, CSS

#27 [STYLE] 라이브보드 컴포넌트 위치 조정
  src/components/LiveBoard/liveboard-broad.vue
  src/components/LiveBoard/liveboard-product.vue
  src/components/LiveBoard/liveboard-prompt.vue
  src/components/LiveBoard/liveboard-statistics.vue
  src/components/LiveBoard/liveboard-time.vue
  src/components/Video/videoplayer.vue
  src/components/liveboard/liveboard-chat.vue
  src/views/broadcast/liveboard.vue
Labels: CSS

#28 [FEAT] 라이브 페이지 상품 구매
  src/assets/images/logo/logo-gpt.png
  src/components/LiveBoard/liveboard-purchase.vue
  src/views/broadcast/live-viewing.vue
Labels: 기능추가, CSS

#29 [FEAT] 상품 통계 페이지 추가
  src/components/Card/analytics-card.vue
  src/components/Card/product-statistics-card.vue
  src/components/Table/statistics-default-table.vue
  src/views/dashboard/product-statistics.vue
Labels: 기능추가, CSS

#30 [FEAT] 최근 본 상품 페이지 추가
  src/components/Card/broadcast-historyCard.vue
  src/components/Card/product-historyCard.vue
  src/components/Order/order-list.vue
  src/components/Order/review-list.vue
  src/views/mypage/broadcast-history.vue
Labels: 기능추가, CSS, 스타일
